### PR TITLE
Edit the content of the NeuroAI session

### PR DESCRIPTION
**Pull request by complexbrains**
This pr initiate the content of the NeuroAI session with a new logo design which is completely prone to change as needed.

### CODE REVIEW

**Comment by emdupre** [comment]
Thank you, @complexbrains !!

It looks like the temporary deployments are no longer active (AFAICT ?), so I can't preview them. But from the files themselves, the site looks great ! The only issue I could see is that you have an extra .DS_Store in there 😸 

Do you want to remove that and merge it ? We can then iterate from there, if you'd like !

**Comment by complexbrains** [comment]
Thank you Elizabeth! Appreciate it a lot! That file somehow missed from my eyes 🙈 I cannot preview it even I changed the deployment of the website to my branch. The deployment passes successfully but the website does not preview. Maybe @pbellec might have an idea.

**Comment by emdupre** [comment]
Ah, I think because it's building from `main` rather than from this branch. This likely makes sense (since the actual site should be built from the main branch rather than from PRs), but if you wanted to modify we'd need to add a file [like the one shown here](https://github.com/actions/jekyll-build-pages) on to the main branch.

Previews aren't yet [out of alpha](https://github.com/actions/deploy-pages/blob/368bf1aa22b9265440e251b9216520e3f91c2d5b/action.yml#L36-L39) for GHA, so we'd either need to either (1) manage PRs from a set `dev` branch, for example, or (2) use another service like netlify to handle PR previewing. 

At this point, I'd suggest we just merge this in and edit from there -- since the site isn't officially advertised yet, I don't think we need to be particularly worried if information is temporarily poorly formatted / misspelled, etc !

**Comment by complexbrains** [comment]
Thank you Elizabeth! Ok, I guess merging it and iterating over the main branch seems like the simplest solution as you suggested. Let me do it with the hope that it will work 😊

**Comment by complexbrains** [comment]
Pierre made a pass on the errors, now I am completing those that I can to try this evening again.

**Comment by emdupre** [comment]
Just to follow-up : The issue is that this was directed to build with Jekyll on GH-pages but it's a Jupyter-Book site, so it needs to be built with the action I added ! I just need to figure out how to disable the zombie Jekyll action.

**Comment by emdupre** [comment]
We need to elevate this to write-access :
Screenshot 2023-07-12 at 15 41 31

@complexbrains if you have permissions, could you update that setting ?

**Comment by complexbrains** [comment]
Oh I see. That makes sense indeed! Thank you so much for looking into it!

Also it didn't let me in the repo but apparently [can be done in the organization level. ](https://github.com/orgs/community/discussions/56704#discussioncomment-6135942) So I made the setting so hope it will work now.

**Comment by complexbrains** [comment]
Thank you so much Elizabeth for deploying all those! They work like a charm! 💐

**Pull request merged**
